### ISSUE TITLE
Create implementation guide for the Standard for Public Code

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/projects#112]
We have received feedback from multiple sources that a guide on how to implement the standard would be valuable. This could include examples, how-to's, templates and further reading that go way beyond what is in the scope for the standard itself.

**Comment by ericherman** [comment]
We have started to sketch out what it might look like: https://hackmd.io/CZJ0hkzRSVSIJ5e0KDZxxA

**Comment by Ainali** [comment]
Since we now have the https://github.com/publiccodenet/community-implementation-guide-standard repository, this issue could be considered solved.
