### ISSUE TITLE
Add BumperScripter

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/projects#13]
As proposed during today's team meeting, the BumperScripter could be added here. Should it be added in Chronological order, or further down since it's a quite small project?

**Comment by ElenaFdR** [comment]
Proposal: take the dates off our current projects (leave them only on past projects). Add the bumperscripter under the governance game (because, as you say, it's a small project).

**Comment by ElenaFdR** [comment]
I've made a draft PR with with the page rearranged as per the comment above so we can easily add the bumperscripter.
