### ISSUE TITLE
Add CC Global Summit video on the Standard

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/projects#15]
It might nice to add in the Standard section on projects.publiccode.net as well.

_Originally posted by @Ainali in https://github.com/publiccodenet/standard/issues/360#issuecomment-714474954_

**Comment by ElenaFdR** [comment]
Is this superseded by the addition of the CITYxCITY course?

**Comment by Ainali** [comment]
Possibly. But my thought was to add the video to the page, not just a link to it, so the result would be very different. But it might also be stalled since I believe we don't have the technical capability yet to add it like that yet.
