### ISSUE TITLE
Consider renaming this repository 

### ISSUE THREAD

**Issue by clausmullie** [publiccodenet/projects#155]
The header title used across our sites that link to the content of this repository is `resources`

However, the title and repo name are `projects`

It may be clearer if we stick to one name. I am personally more in favor of `resources` as it's more indicative of what's available in this repository. However, this might not be easy to change with regards to incoming links. 

[Related issue on the implementation guide repo](https://github.com/publiccodenet/community-implementation-guide-standard/issues/80)

[Related comment](https://github.com/publiccodenet/projects/issues/10#issuecomment-779306233)

**Comment by ericherman** [comment]
We can test this by creating a test repository with a single `index.md` and see how it goes.

**Comment by Ainali** [comment]
We will not do this for now.
