### ISSUE TITLE
Create Governance game video for Mozilla Festival

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/projects#26]
The accepted pitch:

*5 min video introduction to the governance game*
Governance is important, but unless you start out with a really clear vision, it might be hard to get everyone on the same page. People join projects at various times and when the project is small, governance is often not a top priority. Governance usually becomes a priority ex-post, or when a project is already in full implementation. So how do you get agreement and a common understanding on the governance of your codebase? If it wasn't already clear, chances are that people will have different views on what the status quo is. And if discussions are started based on different premises, misunderstandings are bound to happen. That is why we created the Governance Game. The Governance Game (https://github.com/publiccodenet/governance-game) is a fun way to explore how organisations can maintain shared and collaborative open content together. It can help you and your community to start talking about various aspects of governance, and highlight potential pitfalls. In this session we'll show you a few different ways of how you can use this game to enhance your project.

**Comment by Ainali** [comment]
Draft script for video: https://hackmd.io/cfm6ehCtRSKq_rFGm05S9w?view

**Comment by Ainali** [comment]
First very rough draft just to get a sense of the length. My main takeaway is that we can add perhaps another minute (+33%). 

https://user-images.githubusercontent.com/5566159/108208147-f05a1c80-7128-11eb-94ea-de5c65787c26.mp4

**Comment by felixfaassen** [comment]
@Ainali excellent script and video. I would not make it longer. It is great in length and detail. I really like it. Some small suggestions/ideas I had when watching it:

- Maybe also briefly mention in the part where you talk about customizing the game that it can also be used as an exporative tool, so not only from a governance perspective but from business modeling or financing or support perspective (of course al perspectives of governance)
- Great that you show you could add cards. Maybe briefly touch we are open to new ideas and would love to hear stories from people using the game. 
- When you have the final video we should include this one in the README of the governance game

As for the production. I can help you clean up the final dialogue if you want. 

Overall great video! And the rotating card game is of course brilliant ;-)

**Comment by Ainali** [comment]
Those are great ideas! Yes, increasing the length is of course not a goal of itself. We should keep it as short as possible while getting our message across, but since we had some more space we could think of what else we wanted to say, and I believe your suggestions improves our message. I'll try to integrate that into the script!

**Comment by clausmullie** [comment]
Awesome work @Ainali ! <3 

Few small points:
* Coop game -> cooperative game, for those who may be unfamiliar with that jargon
* The video and sound are out of synch for me, but that might just be a problem on my end
* (linked to what Felix suggested) You could consider sharpening a bit more how it is already being used? ie - in addition to formalising a previously informal arrangement, and preparing for scaling of the community, also in market consultations to onboard new vendors (incl business models but also risk and support), to define roles and responsibilities for product and technical steering teams,to help newcomers unfamiliar with open source governance to get a shared vocabulary and understanding

**Comment by Ainali** [comment]
Thanks for the feedback Claus! I changed the script based on your first point immediately. I agree also on the third point. Do you feel that the change I made in the script based on Felix feedback is sharp enough, or should something concrete be mentioned?
(On your second point, it's not a problem in your end. It's different video and audio just as a mock-up.)

**Comment by AlbaRoza** [comment]
@Ainali really liked it, very professional!! I think this is a great precedent to following in pre-recorded talks.

Little suggestions:

1. Would you reconsider synchronizing video + audio? My brain struggles to process that the person that is moving his lips is not saying what I'm hearing.
2. There's something around minute 2.30, like another voice that collides with yours. Not sure if it's intentional or not, though!

**Comment by Ainali** [comment]
Thanks for the feedback @AlbaRoza! 
1. As I mentioned before, the video of me talking isn't even the same talk as my voice (it's from the standard course vide), so the sync is off by a few weeks on purpose. I will record a brand new version of the talk, with video, with the new script.
2. Good point! It was intentional, but if you think it collides it means it disturbs more than what it adds value. I will lower the volume considerably on it.

**Comment by clausmullie** [comment]
@Ainali responding to your question about my second point: 

I checked in on the draft script - particularly the custom usage part. It has the right ingredients, but I think it now relies on the viewer to do the work on how they can apply it to their context. I think perhaps only someone who already understands codebase governance will be able to do that. 

My sense is that the current draft captures most of [this page](https://github.com/publiccodenet/about/blob/develop/activities/supporting-codebase-governance/customized-governance-workshop/index.md), but that it may still be beneficial to sketch some 'problem scenarios' in which people who are not familiar with codebase governance can recognise themselves. 

Focusing on the (types of) problems you can solve, makes it more attractive to the people who won't (yet) recognise the governance game as (part of) a possible solution to their problem.

This could include (iterating on the list I made above):
1) you want more vendors, not sure where to start
2) you want new public reusers, not sure how to go about it
3) there are tensions within the community on merging contributions 
4) you are struggling to define roles and responsibilities within the community

This is perhaps overkill for this video, so this should not be a blocker for the video, but maybe we could consider adding something like this to the governance game repository and then iterating for future videos/talks?

**Comment by clausmullie** [comment]
I went down a rabbit hole and ended up [here](https://lfx.linuxfoundation.org/tools/insights/) - note how they frame potential new user's potential problems in the 'we' form -> if someone accurately expresses your problem, it generally has a much bigger impact on you than them telling you about their solution. Particularly if they can articulate it more clearly and succinctly than you can.

**Comment by Ainali** [comment]
Again, solid feedback @clausmullie! This is so good I have tried to integrate some of it in the script already (and then we can iterate and improve later too).

**Comment by Ainali** [comment]
Here's a second draft. What needs to be done for the final version is to practice enough to get takes where I am not visibly reading the script. This also needs to have a bit of audio cleanup so that the background noise levels are consistent all through the video. I will also reshoot the card handling sequence, so there are no "jump cuts" when we stop making changes to the script. In general, I will also clean up some cuts. 

Points I am specifically looking for feedback on:

- Is the script good enough now?
- Do we want a simple title screen in the beginning?


https://user-images.githubusercontent.com/5566159/109490720-e9b49900-7a88-11eb-9878-e60105767618.mp4

**Comment by ElenaFdR** [comment]
@Ainali, yes and yes!

**Comment by Ainali** [comment]
With title screen (and some tiny polishing in cuts).


https://user-images.githubusercontent.com/5566159/109617528-cc3e0880-7b36-11eb-9d7b-a7bad94f15e4.mp4

**Comment by clausmullie** [comment]
One last afterthought on the describing the solution v the problem balance. Perhaps it could be thought through as:

1) If you describe the solution, you may appeal more to people who are closer to the subject matter, understand their problems and needs, and are may be looking to compare solutions and/or augment their toolbox of solutions
2) If you describe the problem space, you may appeal more to people further from the subject matter, who may not (yet) be able to (accurately) articulate their problems and needs, nor be familiar with the solution types. 

The audience for the first might be a bit bored and unimpressed with the second description, while the audience for the second might not see the relevance, or be overwhelmed, by the first description.

**Comment by Ainali** [comment]
@clausmullie Is this afterthought a response to my last video draft or a continuation of your previous comment?

**Comment by clausmullie** [comment]
Previous comment. Just wanted to put it in words and park it somewhere, as it may be relevant for our other material.

**Comment by Ainali** [comment]
Latest (and possibly final) take.

https://user-images.githubusercontent.com/5566159/109940964-e7de1600-7cd2-11eb-82f1-e926a565abe3.mp4

Anything that *needs* a change, or is this good to go?

**Comment by ericherman** [comment]
Obviously there are some things which could get some polish, like audio consistency, but save that for a future version.

Nothing *needs* a change.
This is good to go.

**Comment by Ainali** [comment]
Published video: https://www.youtube.com/watch?v=Dt0WFla4eeM
