### ISSUE TITLE
Update /talks-and-articles.md with consistent bibliography format

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/projects#27]
On #16, @ainali suggested:

* [Name of the talk](https://example.com/conference/talk-title), by Firstname Lastname at  [Conference](https://example.com/conference/) [[slides](https://example.com/conference/talk-title/slides)] [[video](https://example.com/conference/video)] (Month YYYY) (in Language)

**Comment by Ainali** [comment]
I am happy to take this on, but will wait for the current pull requests to be merged to avoid conflicts.
