### ISSUE TITLE
Apply for live streaming the podcast on our LinkedIn page

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/projects#44]
About the application process: https://www.linkedin.com/help/linkedin/answer/100224

**Comment by Ainali** [comment]
The application has been submitted with @ElenaFdR, @AlbaRoza and me on it.

**Comment by Ainali** [comment]
Request was denied on April 2.

> **Why didn't my application get accepted?**
At the time of submission, your application did not meet one or more of the following criteria:
> - Video, original content and overall content creation history
> - Audience size and engagement history
> - Page and Page Admins have been in good standing on LinkedIn
>
>**What can I do to get access?**
We recommend continuing to build your audience on the platform, creating engaging video content and follow our Professional Community Policies. You may re-apply after 60 days.

**Comment by ElenaFdR** [comment]
I'm going to close this for now. We can try again in June.
