### ISSUE TITLE
Missing talks from 2019/2020/2021

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/projects#48]
- [ ] March 2019: @nebster at #NGI4EU ([tweet](https://twitter.com/MarietjeSchaake/status/1109087746684059649?s=20))
- [ ] April 2019: @nebster at SCORE? ([tweet](https://twitter.com/brynskov/status/1115879164178046976?s=20), [tweet](https://twitter.com/kimsovso/status/1115881560803348482?s=20))
- [ ] April 2019: @bvhme at #Forumpa2019 ([tweet](https://twitter.com/FPA_net/status/1118438289495744512?s=20), [event URL](https://forumpa2019.eventifpa.it/it/event-details/?id=8522))
- [ ] April 2019: Standard launch! @nebster @bvhme spoke! ([tweet](https://twitter.com/MirjamvanTiel/status/1118884287967891456?s=20_), [video](https://drive.google.com/file/d/1QM5iGggrusXv0zhuhuPWn046iW46Pbi6/view) (thanks, [sambutlerUS](https://twitter.com/sambutlerUS/status/1130801250562387968?s=20))
- [ ] May 2019: @nebster at #prixbloxhubinteractive ([tweet thread](https://twitter.com/citiesforpeople/status/1131122751157297152?s=20))
- [ ] May 2019: @nebster at Code for America Summit 2019 ([tweet](https://twitter.com/publiccodenet/status/1133758324070060034?s=20))
- [ ] June 2019: @bvhme at Sharing & Reuse Conference 2019 ([conference program](https://joinup.ec.europa.eu/collection/sharing-and-reuse-it-solutions/sharing-reuse-conference-2019-speakers-and-moderators-0))
- [ ] June 2019: @bvhme at DataLab Amsterdam, timed to coincide with We Make the City 2019 ([event listing](https://www.meetup.com/DataLab-Amsterdam/events/261731838/), [tweet](https://twitter.com/publiccodenet/status/1139176309710569473?s=20))
- [ ] August 2019: @nebster at Techfestival Cophenhagen 2019 (event link is dead, but [tweet](https://twitter.com/publiccodenet/status/1167420408456536065?s=20) and [tweet](https://twitter.com/publiccodenet/status/1169529179446140928?s=20))
- [ ] Nov 2019: #OSSBeyond2020 ([tweet](https://twitter.com/publiccodenet/status/1194893505354772480?s=20) - @Ainali @ericherman @bvhme, was this a talk or just attending?)
- [ ] Nov 2019: @nebster at Smart City World Expo 2019 (shared booth - @nebster, gave a talk in the booth area.  [tweet](https://twitter.com/publiccodenet/status/1196442540528013313?s=20), [tweet](https://twitter.com/oascities/status/1197442578989436928?s=20))
- [ ] Jan 2020: @Ainali and @clausmullie ran the governance game at Connected Smart Cities and Communities Conference ([tweet](https://twitter.com/publiccodenet/status/1218163603574067200?s=20), event page is dead - check internet archive?)
- [ ] attendance but no talks at FOSDEM 2020
- [ ] March 2020: looks like Aligning Public Tech happened?? @AlbaRoza and @Ainali? ([tweet](https://twitter.com/publiccodenet/status/1230120219483475968?s=20), [tweet](https://twitter.com/publiccodenet/status/1238034320285204480?s=20))
- [ ] Aug 2020: @lscheske at Barcamp: Verwaltung. Digital. Gestalten ([tweet](https://twitter.com/publiccodenet/status/1293874879520034816?s=20))
- [ ] Sep 2020: @nebster lightning talk at Next Generation Internet Summit ([tweets + livestream link](https://twitter.com/publiccodenet/status/1310497737167843329?s=20))
- [ ] Sep 2020: @AlbaRoza lightning talk on public code stewardship and tools at Cloud Native: OpenStad herbruikbaar maken voor gemeenten, Kubernetes bij NU.nl ([event URL](https://www.meetup.com/nl-NL/developer-overheid-nl/events/272400965/))
- [ ] March 2021: @lscheske and @nebster at Mozfest ([event listing](https://schedule.mozillafestival.org/session/TDHQ3D-1))
- [ ] March 2021: @AlbaRoza on remote working, Software Development Summit ([tweet](https://twitter.com/publiccodenet/status/1367886519889969155?s=20))
- [ ] March 2021: @bvhme on panel at Public Spaces ([tweet](https://twitter.com/publiccodenet/status/1370346029241995266?s=20))
- [ ] April 2021: @AlbaRoza on panel about Open Source at IWD Connect by Women TechMakers Spain [event URL](https://gdg.community.dev/events/details/google-gdg-asturias-presents-iwd-connect-by-women-techmakers-spain/#/)

Question: should we log events we helped organize but didn't speak at? (For example, [Open Source Developmen of COVID Apps](https://twitter.com/publiccodenet/status/1314165111519612928?s=20) or [Een open source ecosysteem voor de overheid](https://www.meetup.com/Code-For-NL/events/276665525/), where @bvhme is chairing a round table?) Or [our workshop session](https://twitter.com/publiccodenet/status/1317077408290398211?s=20) at Creative Commons Global Summit 2020?

**Comment by Ainali** [comment]
Here's the archived link for the Connected Smart Cities and Communities Conference event: https://web.archive.org/web/20200810162311/https://oasc.events.idloom.com/connected-smart-cities-conference-2020/pages/programme

**Comment by AlbaRoza** [comment]
Just added one!

**Comment by ElenaFdR** [comment]
I'm only going to add talks that were recorded or that we have slides for. Since the current list only includes talks where someone can consume the content afterwards, I feel like adding events without accessible content would make this page less helpful and harder to navigate for someone looking for content.
There's a separate benefit for us in knowing where we've been, but that's already met by the non-public events spreadsheet. It would also be met by [publiccode.net issue 39](https://github.com/publiccodenet/publiccode.net/issues/39).

**Comment by ericherman** [comment]
As it's been more than a month, I'm closing per Elena's recommendation.
