### ISSUE TITLE
"Let’s talk about public code" link geeft 404

### ISSUE THREAD

**Issue by keunes** [publiccodenet/projects#69]
Hallo,

De link [Let’s talk about public code](https://podcast.publiccode.net/) op de projects landingspagina stuurt me naar https://www.podbean.com/site/error?msg=no_owndomain, wat een 404 geeft.

Hebben jullie een nieuw platform voor de podcast, waardoor de link niet meer klopt? (Ik wilde naar het interview over [Signalen](https://signalen.org/news/2021-05-21-interview-'s-hertogenbosch-first-replicator/) luisteren.)

(Mochten jullie de podcast willen self-hosten, is [Castopod](https://code.podlibre.org/podlibre/castopod-host) misschien een goede tip.

**Comment by Ainali** [comment]
Thanks for the report! We will try to fix it ASAP. 

And also thanks for the tip on Castopod, that might be a longterm solution when it gets out of the alpha phase.

**Comment by Ainali** [comment]
@keunes If you want the Signals episode urgently, here is the [live recording on Youtube](https://www.youtube.com/watch?v=zPF_3DpNA0A&list=PL_5ziu2gADmBPPsDlo4sMt1M7Yd8LvOBK&index=5&t=357s).

**Comment by Ainali** [comment]
The URL resolves again, thanks again for the report!

**Comment by keunes** [comment]
Hi @Ainali
Thanks for looking into this, and sorry for reporting in Dutch - I was still in the Signalen mode :p

I just tried again, but I'm still getting the same 404.

**Comment by Ainali** [comment]
No, it seems our own domain didn't get restored even though the site is backup at https://publiccodenet.podbean.com/
We'll take another look!

**Comment by Ainali** [comment]
And now it has been fixed and tested :)

**Comment by keunes** [comment]
Can confirm, thanks again!
