### ISSUE TITLE
Review engineering guidelines of other FOSS foundations to find ones we can recommend to members

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/projects#72]
Engineering guidelines are important, since they influence things like architecture decisions.

Foundations to review (starting list):
- [ ] Apache
- [ ] Linux (if they have anything)
- [ ] Node?
- [ ] Oracle MySQL (style notes)
- [ ] PostgreSQL

**Comment by clausmullie** [comment]
@ericherman is this something you feel might become a priority within the next 3-6 months? If not, can we close this issue?

**Comment by ericherman** [comment]
Closing this issue, we can revisit when it connects to a direct need.
