### ISSUE TITLE
Create brief for stewardship explainer video 

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/projects#79]
We have identified that it would be valuable to have the stewardship process explained in a short video. This issue sets out to create the brief for that video.

**Comment by clausmullie** [comment]
Duplicates [#83 on publiccode.net](https://github.com/publiccodenet/publiccode.net/issues/83)

**Comment by Ainali** [comment]
> Duplicates [#83 on publiccode.net](https://github.com/publiccodenet/publiccode.net/issues/83)

It does not really duplicate it. In order to have one create a video for us, we need to write a brief for it. The other issue seems to assume we should create it ourselves.
